### PR TITLE
Wrap rolls in a spoiler

### PR DESCRIPTION
**Pull request by BenLubar**

### CODE REVIEW

**Comment by BenLubar** [comment]
@yamikuronue it looks like part of the build is failing but it's still able to run :confused:

**Comment by yamikuronue** [comment]
Huh? looks fine to me.

**Comment by BenLubar** [comment]
https://travis-ci.org/yamikuronue/SockLogiDice/jobs/156350197#L536

**Comment by yamikuronue** [comment]
That's all passing....?

The red parenthesis say that it took longer than expected. Which is to be expected, because of the randomization method.

**Comment by BenLubar** [comment]
is it jellypotatoing you?

image

**Comment by yamikuronue** [comment]
...huh. Weird.

**Pull request merged**
